apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-cont-app
  namespace: ai-cont
  labels:
    app: ai-cont-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ai-cont-app
  template:
    metadata:
      labels:
        app: ai-cont-app
    spec:
      initContainers:
      - name: migrate-db
        image: ai-cont-app:latest
        command: ["npx", "prisma", "migrate", "deploy"]
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: DATABASE_URL
        - name: DIRECT_URL
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: DIRECT_URL
      containers:
      - name: ai-cont-app
        image: ai-cont-app:latest
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: NODE_ENV
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: PORT
        - name: HOSTNAME
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: HOSTNAME
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: DATABASE_URL
        - name: DIRECT_URL
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: DIRECT_URL
        livenessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
      imagePullPolicy: IfNotPresent